# Generated by Django 4.2.1 on 2023-05-20 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='product/banner/')),
            ],
            options={
                'verbose_name': 'Banner rasm',
                'verbose_name_plural': 'Banner rasmlar',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='product/brands/')),
            ],
            options={
                'verbose_name': 'Brend',
                'verbose_name_plural': 'Brendlar',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=223)),
                ('title_uz', models.CharField(max_length=223, null=True)),
                ('title_en', models.CharField(max_length=223, null=True)),
                ('title_ru', models.CharField(max_length=223, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('parent_category', models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'parent_category__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.category', verbose_name='Parent Category')),
            ],
            options={
                'verbose_name': 'Mahsulot Kategoriyasi',
                'verbose_name_plural': 'Mahsulot Kategoriyalari',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'NEW'), (1, 'SALE'), (2, 'POPULAR'), (3, 'PREMIUM')], default=0, verbose_name='Holati')),
                ('name', models.CharField(max_length=223, null=True, verbose_name='Maxsulot nomi')),
                ('name_uz', models.CharField(max_length=223, null=True, verbose_name='Maxsulot nomi')),
                ('name_en', models.CharField(max_length=223, null=True, verbose_name='Maxsulot nomi')),
                ('name_ru', models.CharField(max_length=223, null=True, verbose_name='Maxsulot nomi')),
                ('price', models.FloatField(verbose_name='Tan narxi')),
                ('discount', models.FloatField(blank=True, null=True, verbose_name='Chegirma')),
                ('made_in', models.CharField(max_length=50, verbose_name='Ishlab chiqarilgan davlat')),
                ('consists', models.TextField(verbose_name="Maxsulot haqida ma'lumot")),
                ('consists_uz', models.TextField(null=True, verbose_name="Maxsulot haqida ma'lumot")),
                ('consists_en', models.TextField(null=True, verbose_name="Maxsulot haqida ma'lumot")),
                ('consists_ru', models.TextField(null=True, verbose_name="Maxsulot haqida ma'lumot")),
                ('capacity', models.CharField(blank=True, max_length=20, null=True, verbose_name="Maxsulotning og'irligi")),
                ('guarantee', models.CharField(blank=True, max_length=30, null=True, verbose_name='Maxsulot kafolati')),
                ('is_active', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.brand')),
                ('category', models.ManyToManyField(blank=True, limit_choices_to={'is_active': True, 'parent_category__isnull': False}, to='product.category')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='product/product_image/')),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_images', to='product.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
