# Generated by Django 4.2.1 on 2023-05-22 15:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='consists',
            field=ckeditor.fields.RichTextField(verbose_name="Maxsulot haqida ma'lumot"),
        ),
        migrations.AlterField(
            model_name='product',
            name='consists_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name="Maxsulot haqida ma'lumot"),
        ),
        migrations.AlterField(
            model_name='product',
            name='consists_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name="Maxsulot haqida ma'lumot"),
        ),
        migrations.AlterField(
            model_name='product',
            name='consists_uz',
            field=ckeditor.fields.RichTextField(null=True, verbose_name="Maxsulot haqida ma'lumot"),
        ),
    ]
