# Generated by Django 4.2.1 on 2023-05-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_alter_product_consists_alter_product_consists_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="rating",
            field=models.PositiveIntegerField(default=80, max_length=100),
        ),
    ]
